name: wind-energy-plotting
channels:
  - conda-forge
  - defaults
dependencies:
  - netcdf4=1.5.3
  - numpy=1.15.4
  - pandas=0.23.4
  - xarray=0.11.0
  - cartopy=0.18.0
  - wrf-python=1.3.2
  - cmocean=2.0
  - arm_pyart=1.11.1
