name: wind-energy-plotting-updated
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.7
  - netcdf4==1.6.5
  - numpy==1.26.3
  - pandas==2.2.0
  - xarray==2024.1.0
  - cartopy==0.22.0
  - wrf-python==1.3.4.1
  - cmocean==3.0.3
  - arm_pyart==1.17.0
  - matplotlib==3.8.2
  - cool_maps==0.0.9
